name: Print Secret Without Spaces

on: [push]

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret Without Spaces
        run: echo "${{ secrets.YOUR_SECRET }}" | sed 's/ //g'
