name: Print Secret Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print secret with spaces
      run: echo "${{ secrets.PRINT_SECRET }}" | sed 's/./& /g'ls
